linters-settings:
  govet:
    check-shadowing: true
  golint:
    min-confidence: 0
  gocyclo:
    min-complexity: 10
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 3
  misspell:
    locale: US
  lll:
    line-length: 120
  goimports:
    local-prefixes: github.com/HotCodeGroup/warscript-games
  gocritic:
    enabled-tags:
      - performance
      - style
      - experimental
linters:
  enable-all: true
  disable:
    - depguard
    - maligned
    - prealloc
    - gochecknoglobals
    - gochecknoinits
run:
  skip-files:
    - game_model_test.go
    - grpc_test.go
    - http_test.go
    - test_structures.go